package com.liudehuang.item.api.model.domain;

import java.util.Date;

public class ItemParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.attribute_flag
     *
     * @mbggenerated
     */
    private Integer attributeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.attribute_name
     *
     * @mbggenerated
     */
    private String attributeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.attribute_value
     *
     * @mbggenerated
     */
    private String attributeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_param.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.id
     *
     * @return the value of t_item_param.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.id
     *
     * @param id the value for t_item_param.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.merchant_id
     *
     * @return the value of t_item_param.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.merchant_id
     *
     * @param merchantId the value for t_item_param.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.item_no
     *
     * @return the value of t_item_param.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.item_no
     *
     * @param itemNo the value for t_item_param.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.attribute_flag
     *
     * @return the value of t_item_param.attribute_flag
     *
     * @mbggenerated
     */
    public Integer getAttributeFlag() {
        return attributeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.attribute_flag
     *
     * @param attributeFlag the value for t_item_param.attribute_flag
     *
     * @mbggenerated
     */
    public void setAttributeFlag(Integer attributeFlag) {
        this.attributeFlag = attributeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.attribute_name
     *
     * @return the value of t_item_param.attribute_name
     *
     * @mbggenerated
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.attribute_name
     *
     * @param attributeName the value for t_item_param.attribute_name
     *
     * @mbggenerated
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName == null ? null : attributeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.attribute_value
     *
     * @return the value of t_item_param.attribute_value
     *
     * @mbggenerated
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.attribute_value
     *
     * @param attributeValue the value for t_item_param.attribute_value
     *
     * @mbggenerated
     */
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.created_time
     *
     * @return the value of t_item_param.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.created_time
     *
     * @param createdTime the value for t_item_param.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.created_by
     *
     * @return the value of t_item_param.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.created_by
     *
     * @param createdBy the value for t_item_param.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.updated_time
     *
     * @return the value of t_item_param.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.updated_time
     *
     * @param updatedTime the value for t_item_param.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.updated_by
     *
     * @return the value of t_item_param.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.updated_by
     *
     * @param updatedBy the value for t_item_param.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.remark
     *
     * @return the value of t_item_param.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.remark
     *
     * @param remark the value for t_item_param.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_param.deleted
     *
     * @return the value of t_item_param.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_param.deleted
     *
     * @param deleted the value for t_item_param.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}