package com.liudehuang.item.api.model.domain;

import java.math.BigDecimal;
import java.util.Date;

public class ItemSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.item_sku_no
     *
     * @mbggenerated
     */
    private String itemSkuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.item_sku_name
     *
     * @mbggenerated
     */
    private String itemSkuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.specifications
     *
     * @mbggenerated
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.item_sku_pic
     *
     * @mbggenerated
     */
    private String itemSkuPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.item_sku_price
     *
     * @mbggenerated
     */
    private BigDecimal itemSkuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_sku.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.id
     *
     * @return the value of t_item_sku.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.id
     *
     * @param id the value for t_item_sku.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.merchant_id
     *
     * @return the value of t_item_sku.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.merchant_id
     *
     * @param merchantId the value for t_item_sku.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.item_no
     *
     * @return the value of t_item_sku.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.item_no
     *
     * @param itemNo the value for t_item_sku.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.item_sku_no
     *
     * @return the value of t_item_sku.item_sku_no
     *
     * @mbggenerated
     */
    public String getItemSkuNo() {
        return itemSkuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.item_sku_no
     *
     * @param itemSkuNo the value for t_item_sku.item_sku_no
     *
     * @mbggenerated
     */
    public void setItemSkuNo(String itemSkuNo) {
        this.itemSkuNo = itemSkuNo == null ? null : itemSkuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.item_sku_name
     *
     * @return the value of t_item_sku.item_sku_name
     *
     * @mbggenerated
     */
    public String getItemSkuName() {
        return itemSkuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.item_sku_name
     *
     * @param itemSkuName the value for t_item_sku.item_sku_name
     *
     * @mbggenerated
     */
    public void setItemSkuName(String itemSkuName) {
        this.itemSkuName = itemSkuName == null ? null : itemSkuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.specifications
     *
     * @return the value of t_item_sku.specifications
     *
     * @mbggenerated
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.specifications
     *
     * @param specifications the value for t_item_sku.specifications
     *
     * @mbggenerated
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.item_sku_pic
     *
     * @return the value of t_item_sku.item_sku_pic
     *
     * @mbggenerated
     */
    public String getItemSkuPic() {
        return itemSkuPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.item_sku_pic
     *
     * @param itemSkuPic the value for t_item_sku.item_sku_pic
     *
     * @mbggenerated
     */
    public void setItemSkuPic(String itemSkuPic) {
        this.itemSkuPic = itemSkuPic == null ? null : itemSkuPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.item_sku_price
     *
     * @return the value of t_item_sku.item_sku_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemSkuPrice() {
        return itemSkuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.item_sku_price
     *
     * @param itemSkuPrice the value for t_item_sku.item_sku_price
     *
     * @mbggenerated
     */
    public void setItemSkuPrice(BigDecimal itemSkuPrice) {
        this.itemSkuPrice = itemSkuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.stock
     *
     * @return the value of t_item_sku.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.stock
     *
     * @param stock the value for t_item_sku.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.created_time
     *
     * @return the value of t_item_sku.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.created_time
     *
     * @param createdTime the value for t_item_sku.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.created_by
     *
     * @return the value of t_item_sku.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.created_by
     *
     * @param createdBy the value for t_item_sku.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.updated_time
     *
     * @return the value of t_item_sku.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.updated_time
     *
     * @param updatedTime the value for t_item_sku.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.updated_by
     *
     * @return the value of t_item_sku.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.updated_by
     *
     * @param updatedBy the value for t_item_sku.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.remark
     *
     * @return the value of t_item_sku.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.remark
     *
     * @param remark the value for t_item_sku.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_sku.deleted
     *
     * @return the value of t_item_sku.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_sku.deleted
     *
     * @param deleted the value for t_item_sku.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}