package com.liudehuang.item.mapper;

import com.liudehuang.item.model.domain.ItemFootprint;

public interface ItemFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_footprint
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_footprint
     *
     * @mbggenerated
     */
    int insert(ItemFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_footprint
     *
     * @mbggenerated
     */
    int insertSelective(ItemFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_footprint
     *
     * @mbggenerated
     */
    ItemFootprint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_footprint
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_footprint
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemFootprint record);
}