package com.liudehuang.item.model.domain;

import java.util.Date;

public class ItemCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.category_no
     *
     * @mbggenerated
     */
    private String categoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.category_icon
     *
     * @mbggenerated
     */
    private String categoryIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.category_pic
     *
     * @mbggenerated
     */
    private String categoryPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.parent_category_id
     *
     * @mbggenerated
     */
    private String parentCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.category_level
     *
     * @mbggenerated
     */
    private Integer categoryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.category_sort
     *
     * @mbggenerated
     */
    private Integer categorySort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_category.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.id
     *
     * @return the value of t_item_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.id
     *
     * @param id the value for t_item_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.merchant_id
     *
     * @return the value of t_item_category.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.merchant_id
     *
     * @param merchantId the value for t_item_category.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.category_no
     *
     * @return the value of t_item_category.category_no
     *
     * @mbggenerated
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.category_no
     *
     * @param categoryNo the value for t_item_category.category_no
     *
     * @mbggenerated
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo == null ? null : categoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.category_icon
     *
     * @return the value of t_item_category.category_icon
     *
     * @mbggenerated
     */
    public String getCategoryIcon() {
        return categoryIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.category_icon
     *
     * @param categoryIcon the value for t_item_category.category_icon
     *
     * @mbggenerated
     */
    public void setCategoryIcon(String categoryIcon) {
        this.categoryIcon = categoryIcon == null ? null : categoryIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.category_pic
     *
     * @return the value of t_item_category.category_pic
     *
     * @mbggenerated
     */
    public String getCategoryPic() {
        return categoryPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.category_pic
     *
     * @param categoryPic the value for t_item_category.category_pic
     *
     * @mbggenerated
     */
    public void setCategoryPic(String categoryPic) {
        this.categoryPic = categoryPic == null ? null : categoryPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.parent_category_id
     *
     * @return the value of t_item_category.parent_category_id
     *
     * @mbggenerated
     */
    public String getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.parent_category_id
     *
     * @param parentCategoryId the value for t_item_category.parent_category_id
     *
     * @mbggenerated
     */
    public void setParentCategoryId(String parentCategoryId) {
        this.parentCategoryId = parentCategoryId == null ? null : parentCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.category_level
     *
     * @return the value of t_item_category.category_level
     *
     * @mbggenerated
     */
    public Integer getCategoryLevel() {
        return categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.category_level
     *
     * @param categoryLevel the value for t_item_category.category_level
     *
     * @mbggenerated
     */
    public void setCategoryLevel(Integer categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.category_sort
     *
     * @return the value of t_item_category.category_sort
     *
     * @mbggenerated
     */
    public Integer getCategorySort() {
        return categorySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.category_sort
     *
     * @param categorySort the value for t_item_category.category_sort
     *
     * @mbggenerated
     */
    public void setCategorySort(Integer categorySort) {
        this.categorySort = categorySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.category_name
     *
     * @return the value of t_item_category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.category_name
     *
     * @param categoryName the value for t_item_category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.created_time
     *
     * @return the value of t_item_category.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.created_time
     *
     * @param createdTime the value for t_item_category.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.created_by
     *
     * @return the value of t_item_category.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.created_by
     *
     * @param createdBy the value for t_item_category.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.updated_time
     *
     * @return the value of t_item_category.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.updated_time
     *
     * @param updatedTime the value for t_item_category.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.updated_by
     *
     * @return the value of t_item_category.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.updated_by
     *
     * @param updatedBy the value for t_item_category.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.remark
     *
     * @return the value of t_item_category.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.remark
     *
     * @param remark the value for t_item_category.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_category.deleted
     *
     * @return the value of t_item_category.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_category.deleted
     *
     * @param deleted the value for t_item_category.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}