package com.liudehuang.item.model.domain;

import java.util.Date;

public class ItemBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_no
     *
     * @mbggenerated
     */
    private String brandNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_logo
     *
     * @mbggenerated
     */
    private String brandLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_url
     *
     * @mbggenerated
     */
    private String brandUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_desc
     *
     * @mbggenerated
     */
    private String brandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_sort
     *
     * @mbggenerated
     */
    private Integer brandSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.id
     *
     * @return the value of t_item_brand.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.id
     *
     * @param id the value for t_item_brand.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.merchant_id
     *
     * @return the value of t_item_brand.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.merchant_id
     *
     * @param merchantId the value for t_item_brand.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_no
     *
     * @return the value of t_item_brand.brand_no
     *
     * @mbggenerated
     */
    public String getBrandNo() {
        return brandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_no
     *
     * @param brandNo the value for t_item_brand.brand_no
     *
     * @mbggenerated
     */
    public void setBrandNo(String brandNo) {
        this.brandNo = brandNo == null ? null : brandNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_name
     *
     * @return the value of t_item_brand.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_name
     *
     * @param brandName the value for t_item_brand.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_logo
     *
     * @return the value of t_item_brand.brand_logo
     *
     * @mbggenerated
     */
    public String getBrandLogo() {
        return brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_logo
     *
     * @param brandLogo the value for t_item_brand.brand_logo
     *
     * @mbggenerated
     */
    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo == null ? null : brandLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_url
     *
     * @return the value of t_item_brand.brand_url
     *
     * @mbggenerated
     */
    public String getBrandUrl() {
        return brandUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_url
     *
     * @param brandUrl the value for t_item_brand.brand_url
     *
     * @mbggenerated
     */
    public void setBrandUrl(String brandUrl) {
        this.brandUrl = brandUrl == null ? null : brandUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_desc
     *
     * @return the value of t_item_brand.brand_desc
     *
     * @mbggenerated
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_desc
     *
     * @param brandDesc the value for t_item_brand.brand_desc
     *
     * @mbggenerated
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc == null ? null : brandDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_sort
     *
     * @return the value of t_item_brand.brand_sort
     *
     * @mbggenerated
     */
    public Integer getBrandSort() {
        return brandSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_sort
     *
     * @param brandSort the value for t_item_brand.brand_sort
     *
     * @mbggenerated
     */
    public void setBrandSort(Integer brandSort) {
        this.brandSort = brandSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.created_time
     *
     * @return the value of t_item_brand.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.created_time
     *
     * @param createdTime the value for t_item_brand.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.created_by
     *
     * @return the value of t_item_brand.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.created_by
     *
     * @param createdBy the value for t_item_brand.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.updated_time
     *
     * @return the value of t_item_brand.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.updated_time
     *
     * @param updatedTime the value for t_item_brand.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.updated_by
     *
     * @return the value of t_item_brand.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.updated_by
     *
     * @param updatedBy the value for t_item_brand.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.remark
     *
     * @return the value of t_item_brand.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.remark
     *
     * @param remark the value for t_item_brand.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.deleted
     *
     * @return the value of t_item_brand.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.deleted
     *
     * @param deleted the value for t_item_brand.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}